// generated by go run gen.go -output mustache_spec_test.go; DO NOT EDIT

package mustache

import (
	"os"
	"strings"
	"testing"
)

func convertHTMLCharsToExpectedFormat(s string) string {
	return strings.Replace(s, "&#34;", "&quot;", -1)
}

func generatePartial(name string, content string) {
	fo, err := os.Create(name)
	if err != nil {
		panic(err)
	}
	defer func() {
		if err := fo.Close(); err != nil {
			panic(err)
		}
	}()
	if _, err := fo.Write([]byte(content)); err != nil {
		panic(err)
	}
}

func testSpec(t *testing.T,
	template string,
	expected string,
	context interface{}) {
	output := convertHTMLCharsToExpectedFormat(Render(template, context))
	if output != expected {
		t.Errorf("%q\nexpected: %q\nbut got:  %q",
			template, expected, output)
	}
}

func TestCommentsInline(t *testing.T) {
	testSpec(t,
		"12345{{! Comment Block! }}67890",
		"1234567890",
		map[string]interface{}{})
}

func TestCommentsMultiline(t *testing.T) {
	testSpec(t,
		"12345{{!\n  This is a\n  multi-line comment...\n}}67890\n",
		"1234567890\n",
		map[string]interface{}{})
}

func TestCommentsStandalone(t *testing.T) {
	testSpec(t,
		"Begin.\n{{! Comment Block! }}\nEnd.\n",
		"Begin.\nEnd.\n",
		map[string]interface{}{})
}

func TestCommentsIndentedStandalone(t *testing.T) {
	testSpec(t,
		"Begin.\n  {{! Indented Comment Block! }}\nEnd.\n",
		"Begin.\nEnd.\n",
		map[string]interface{}{})
}

func TestCommentsStandaloneLineEndings(t *testing.T) {
	testSpec(t,
		"|\r\n{{! Standalone Comment }}\r\n|",
		"|\r\n|",
		map[string]interface{}{})
}

func TestCommentsStandaloneWithoutPreviousLine(t *testing.T) {
	testSpec(t,
		"  {{! I'm Still Standalone }}\n!",
		"!",
		map[string]interface{}{})
}

func TestCommentsStandaloneWithoutNewline(t *testing.T) {
	testSpec(t,
		"!\n  {{! I'm Still Standalone }}",
		"!\n",
		map[string]interface{}{})
}

func TestCommentsMultilineStandalone(t *testing.T) {
	testSpec(t,
		"Begin.\n{{!\nSomething's going on here...\n}}\nEnd.\n",
		"Begin.\nEnd.\n",
		map[string]interface{}{})
}

func TestCommentsIndentedMultilineStandalone(t *testing.T) {
	testSpec(t,
		"Begin.\n  {{!\n    Something's going on here...\n  }}\nEnd.\n",
		"Begin.\nEnd.\n",
		map[string]interface{}{})
}

func TestCommentsIndentedInline(t *testing.T) {
	testSpec(t,
		"  12 {{! 34 }}\n",
		"  12 \n",
		map[string]interface{}{})
}

func TestCommentsSurroundingWhitespace(t *testing.T) {
	testSpec(t,
		"12345 {{! Comment Block! }} 67890",
		"12345  67890",
		map[string]interface{}{})
}

func TestDelimitersPairBehavior(t *testing.T) {
	testSpec(t,
		"{{=<% %>=}}(<%text%>)",
		"(Hey!)",
		map[string]interface{}{"text": "Hey!"})
}

func TestDelimitersSpecialCharacters(t *testing.T) {
	testSpec(t,
		"({{=[ ]=}}[text])",
		"(It worked!)",
		map[string]interface{}{"text": "It worked!"})
}

func TestDelimitersSections(t *testing.T) {
	testSpec(t,
		"[\n{{#section}}\n  {{data}}\n  |data|\n{{/section}}\n\n{{= | | =}}\n|#section|\n  {{data}}\n  |data|\n|/section|\n]\n",
		"[\n  I got interpolated.\n  |data|\n\n  {{data}}\n  I got interpolated.\n]\n",
		map[string]interface{}{"section": true, "data": "I got interpolated."})
}

func TestDelimitersInvertedSections(t *testing.T) {
	testSpec(t,
		"[\n{{^section}}\n  {{data}}\n  |data|\n{{/section}}\n\n{{= | | =}}\n|^section|\n  {{data}}\n  |data|\n|/section|\n]\n",
		"[\n  I got interpolated.\n  |data|\n\n  {{data}}\n  I got interpolated.\n]\n",
		map[string]interface{}{"section": false, "data": "I got interpolated."})
}

func TestDelimitersPartialInheritence(t *testing.T) {
	generatePartial("include.mustache", ".{{value}}.")
	defer os.Remove("include.mustache")
	testSpec(t,
		"[ {{>include}} ]\n{{= | | =}}\n[ |>include| ]\n",
		"[ .yes. ]\n[ .yes. ]\n",
		map[string]interface{}{"value": "yes"})
}

func TestDelimitersPostPartialBehavior(t *testing.T) {
	generatePartial("include.mustache", ".{{value}}. {{= | | =}} .|value|.")
	defer os.Remove("include.mustache")
	testSpec(t,
		"[ {{>include}} ]\n[ .{{value}}.  .|value|. ]\n",
		"[ .yes.  .yes. ]\n[ .yes.  .|value|. ]\n",
		map[string]interface{}{"value": "yes"})
}

func TestDelimitersSurroundingWhitespace(t *testing.T) {
	testSpec(t,
		"| {{=@ @=}} |",
		"|  |",
		map[string]interface{}{})
}

func TestDelimitersOutlyingWhitespaceInline(t *testing.T) {
	testSpec(t,
		" | {{=@ @=}}\n",
		" | \n",
		map[string]interface{}{})
}

func TestDelimitersStandaloneTag(t *testing.T) {
	testSpec(t,
		"Begin.\n{{=@ @=}}\nEnd.\n",
		"Begin.\nEnd.\n",
		map[string]interface{}{})
}

func TestDelimitersIndentedStandaloneTag(t *testing.T) {
	testSpec(t,
		"Begin.\n  {{=@ @=}}\nEnd.\n",
		"Begin.\nEnd.\n",
		map[string]interface{}{})
}

func TestDelimitersStandaloneLineEndings(t *testing.T) {
	testSpec(t,
		"|\r\n{{= @ @ =}}\r\n|",
		"|\r\n|",
		map[string]interface{}{})
}

func TestDelimitersStandaloneWithoutPreviousLine(t *testing.T) {
	testSpec(t,
		"  {{=@ @=}}\n=",
		"=",
		map[string]interface{}{})
}

func TestDelimitersStandaloneWithoutNewline(t *testing.T) {
	testSpec(t,
		"=\n  {{=@ @=}}",
		"=\n",
		map[string]interface{}{})
}

func TestDelimitersPairwithPadding(t *testing.T) {
	testSpec(t,
		"|{{= @   @ =}}|",
		"||",
		map[string]interface{}{})
}

func TestInterpolationNoInterpolation(t *testing.T) {
	testSpec(t,
		"Hello from {Mustache}!\n",
		"Hello from {Mustache}!\n",
		map[string]interface{}{})
}

func TestInterpolationBasicInterpolation(t *testing.T) {
	testSpec(t,
		"Hello, {{subject}}!\n",
		"Hello, world!\n",
		map[string]interface{}{"subject": "world"})
}

func TestInterpolationHTMLEscaping(t *testing.T) {
	testSpec(t,
		"These characters should be HTML escaped: {{forbidden}}\n",
		"These characters should be HTML escaped: &amp; &quot; &lt; &gt;\n",
		map[string]interface{}{"forbidden": "& \" < >"})
}

func TestInterpolationTripleMustache(t *testing.T) {
	testSpec(t,
		"These characters should not be HTML escaped: {{{forbidden}}}\n",
		"These characters should not be HTML escaped: & \" < >\n",
		map[string]interface{}{"forbidden": "& \" < >"})
}

func TestInterpolationAmpersand(t *testing.T) {
	testSpec(t,
		"These characters should not be HTML escaped: {{&forbidden}}\n",
		"These characters should not be HTML escaped: & \" < >\n",
		map[string]interface{}{"forbidden": "& \" < >"})
}

func TestInterpolationBasicIntegerInterpolation(t *testing.T) {
	testSpec(t,
		"\"{{mph}} miles an hour!\"",
		"\"85 miles an hour!\"",
		map[string]interface{}{"mph": 85})
}

func TestInterpolationTripleMustacheIntegerInterpolation(t *testing.T) {
	testSpec(t,
		"\"{{{mph}}} miles an hour!\"",
		"\"85 miles an hour!\"",
		map[string]interface{}{"mph": 85})
}

func TestInterpolationAmpersandIntegerInterpolation(t *testing.T) {
	testSpec(t,
		"\"{{&mph}} miles an hour!\"",
		"\"85 miles an hour!\"",
		map[string]interface{}{"mph": 85})
}

func TestInterpolationBasicDecimalInterpolation(t *testing.T) {
	testSpec(t,
		"\"{{power}} jiggawatts!\"",
		"\"1.21 jiggawatts!\"",
		map[string]interface{}{"power": 1.21})
}

func TestInterpolationTripleMustacheDecimalInterpolation(t *testing.T) {
	testSpec(t,
		"\"{{{power}}} jiggawatts!\"",
		"\"1.21 jiggawatts!\"",
		map[string]interface{}{"power": 1.21})
}

func TestInterpolationAmpersandDecimalInterpolation(t *testing.T) {
	testSpec(t,
		"\"{{&power}} jiggawatts!\"",
		"\"1.21 jiggawatts!\"",
		map[string]interface{}{"power": 1.21})
}

func TestInterpolationBasicContextMissInterpolation(t *testing.T) {
	testSpec(t,
		"I ({{cannot}}) be seen!",
		"I () be seen!",
		map[string]interface{}{})
}

func TestInterpolationTripleMustacheContextMissInterpolation(t *testing.T) {
	testSpec(t,
		"I ({{{cannot}}}) be seen!",
		"I () be seen!",
		map[string]interface{}{})
}

func TestInterpolationAmpersandContextMissInterpolation(t *testing.T) {
	testSpec(t,
		"I ({{&cannot}}) be seen!",
		"I () be seen!",
		map[string]interface{}{})
}

func TestInterpolationDottedNamesBasicInterpolation(t *testing.T) {
	testSpec(t,
		"\"{{person.name}}\" == \"{{#person}}{{name}}{{/person}}\"",
		"\"Joe\" == \"Joe\"",
		map[string]interface{}{"person": map[string]interface{}{"name": "Joe"}})
}

func TestInterpolationDottedNamesTripleMustacheInterpolation(t *testing.T) {
	testSpec(t,
		"\"{{{person.name}}}\" == \"{{#person}}{{{name}}}{{/person}}\"",
		"\"Joe\" == \"Joe\"",
		map[string]interface{}{"person": map[string]interface{}{"name": "Joe"}})
}

func TestInterpolationDottedNamesAmpersandInterpolation(t *testing.T) {
	testSpec(t,
		"\"{{&person.name}}\" == \"{{#person}}{{&name}}{{/person}}\"",
		"\"Joe\" == \"Joe\"",
		map[string]interface{}{"person": map[string]interface{}{"name": "Joe"}})
}

func TestInterpolationDottedNamesArbitraryDepth(t *testing.T) {
	testSpec(t,
		"\"{{a.b.c.d.e.name}}\" == \"Phil\"",
		"\"Phil\" == \"Phil\"",
		map[string]interface{}{"a": map[string]interface{}{"b": map[string]interface{}{"c": map[string]interface{}{"d": map[string]interface{}{"e": map[string]interface{}{"name": "Phil"}}}}}})
}

func TestInterpolationDottedNamesBrokenChains(t *testing.T) {
	testSpec(t,
		"\"{{a.b.c}}\" == \"\"",
		"\"\" == \"\"",
		map[string]interface{}{"a": map[string]interface{}{}})
}

func TestInterpolationDottedNamesBrokenChainResolution(t *testing.T) {
	testSpec(t,
		"\"{{a.b.c.name}}\" == \"\"",
		"\"\" == \"\"",
		map[string]interface{}{"a": map[string]interface{}{"b": map[string]interface{}{}}, "c": map[string]interface{}{"name": "Jim"}})
}

func TestInterpolationDottedNamesInitialResolution(t *testing.T) {
	testSpec(t,
		"\"{{#a}}{{b.c.d.e.name}}{{/a}}\" == \"Phil\"",
		"\"Phil\" == \"Phil\"",
		map[string]interface{}{"a": map[string]interface{}{"b": map[string]interface{}{"c": map[string]interface{}{"d": map[string]interface{}{"e": map[string]interface{}{"name": "Phil"}}}}}, "b": map[string]interface{}{"c": map[string]interface{}{"d": map[string]interface{}{"e": map[string]interface{}{"name": "Wrong"}}}}})
}

func TestInterpolationInterpolationSurroundingWhitespace(t *testing.T) {
	testSpec(t,
		"| {{string}} |",
		"| --- |",
		map[string]interface{}{"string": "---"})
}

func TestInterpolationTripleMustacheSurroundingWhitespace(t *testing.T) {
	testSpec(t,
		"| {{{string}}} |",
		"| --- |",
		map[string]interface{}{"string": "---"})
}

func TestInterpolationAmpersandSurroundingWhitespace(t *testing.T) {
	testSpec(t,
		"| {{&string}} |",
		"| --- |",
		map[string]interface{}{"string": "---"})
}

func TestInterpolationInterpolationStandalone(t *testing.T) {
	testSpec(t,
		"  {{string}}\n",
		"  ---\n",
		map[string]interface{}{"string": "---"})
}

func TestInterpolationTripleMustacheStandalone(t *testing.T) {
	testSpec(t,
		"  {{{string}}}\n",
		"  ---\n",
		map[string]interface{}{"string": "---"})
}

func TestInterpolationAmpersandStandalone(t *testing.T) {
	testSpec(t,
		"  {{&string}}\n",
		"  ---\n",
		map[string]interface{}{"string": "---"})
}

func TestInterpolationInterpolationWithPadding(t *testing.T) {
	testSpec(t,
		"|{{ string }}|",
		"|---|",
		map[string]interface{}{"string": "---"})
}

func TestInterpolationTripleMustacheWithPadding(t *testing.T) {
	testSpec(t,
		"|{{{ string }}}|",
		"|---|",
		map[string]interface{}{"string": "---"})
}

func TestInterpolationAmpersandWithPadding(t *testing.T) {
	testSpec(t,
		"|{{& string }}|",
		"|---|",
		map[string]interface{}{"string": "---"})
}

func TestInvertedFalsey(t *testing.T) {
	testSpec(t,
		"\"{{^boolean}}This should be rendered.{{/boolean}}\"",
		"\"This should be rendered.\"",
		map[string]interface{}{"boolean": false})
}

func TestInvertedTruthy(t *testing.T) {
	testSpec(t,
		"\"{{^boolean}}This should not be rendered.{{/boolean}}\"",
		"\"\"",
		map[string]interface{}{"boolean": true})
}

func TestInvertedContext(t *testing.T) {
	testSpec(t,
		"\"{{^context}}Hi {{name}}.{{/context}}\"",
		"\"\"",
		map[string]interface{}{"context": map[string]interface{}{"name": "Joe"}})
}

func TestInvertedList(t *testing.T) {
	testSpec(t,
		"\"{{^list}}{{n}}{{/list}}\"",
		"\"\"",
		map[string]interface{}{"list": []interface{}{map[string]interface{}{"n": 1}, map[string]interface{}{"n": 2}, map[string]interface{}{"n": 3}}})
}

func TestInvertedEmptyList(t *testing.T) {
	testSpec(t,
		"\"{{^list}}Yay lists!{{/list}}\"",
		"\"Yay lists!\"",
		map[string]interface{}{"list": []interface{}{}})
}

func TestInvertedDoubled(t *testing.T) {
	testSpec(t,
		"{{^bool}}\n* first\n{{/bool}}\n* {{two}}\n{{^bool}}\n* third\n{{/bool}}\n",
		"* first\n* second\n* third\n",
		map[string]interface{}{"two": "second", "bool": false})
}

func TestInvertedNestedFalsey(t *testing.T) {
	testSpec(t,
		"| A {{^bool}}B {{^bool}}C{{/bool}} D{{/bool}} E |",
		"| A B C D E |",
		map[string]interface{}{"bool": false})
}

func TestInvertedNestedTruthy(t *testing.T) {
	testSpec(t,
		"| A {{^bool}}B {{^bool}}C{{/bool}} D{{/bool}} E |",
		"| A  E |",
		map[string]interface{}{"bool": true})
}

func TestInvertedContextMisses(t *testing.T) {
	testSpec(t,
		"[{{^missing}}Cannot find key 'missing'!{{/missing}}]",
		"[Cannot find key 'missing'!]",
		map[string]interface{}{})
}

func TestInvertedDottedNamesTruthy(t *testing.T) {
	testSpec(t,
		"\"{{^a.b.c}}Not Here{{/a.b.c}}\" == \"\"",
		"\"\" == \"\"",
		map[string]interface{}{"a": map[string]interface{}{"b": map[string]interface{}{"c": true}}})
}

func TestInvertedDottedNamesFalsey(t *testing.T) {
	testSpec(t,
		"\"{{^a.b.c}}Not Here{{/a.b.c}}\" == \"Not Here\"",
		"\"Not Here\" == \"Not Here\"",
		map[string]interface{}{"a": map[string]interface{}{"b": map[string]interface{}{"c": false}}})
}

func TestInvertedDottedNamesBrokenChains(t *testing.T) {
	testSpec(t,
		"\"{{^a.b.c}}Not Here{{/a.b.c}}\" == \"Not Here\"",
		"\"Not Here\" == \"Not Here\"",
		map[string]interface{}{"a": map[string]interface{}{}})
}

func TestInvertedSurroundingWhitespace(t *testing.T) {
	testSpec(t,
		" | {{^boolean}}\t|\t{{/boolean}} | \n",
		" | \t|\t | \n",
		map[string]interface{}{"boolean": false})
}

func TestInvertedInternalWhitespace(t *testing.T) {
	testSpec(t,
		" | {{^boolean}} {{! Important Whitespace }}\n {{/boolean}} | \n",
		" |  \n  | \n",
		map[string]interface{}{"boolean": false})
}

func TestInvertedIndentedInlineSections(t *testing.T) {
	testSpec(t,
		" {{^boolean}}NO{{/boolean}}\n {{^boolean}}WAY{{/boolean}}\n",
		" NO\n WAY\n",
		map[string]interface{}{"boolean": false})
}

func TestInvertedStandaloneLines(t *testing.T) {
	testSpec(t,
		"| This Is\n{{^boolean}}\n|\n{{/boolean}}\n| A Line\n",
		"| This Is\n|\n| A Line\n",
		map[string]interface{}{"boolean": false})
}

func TestInvertedStandaloneIndentedLines(t *testing.T) {
	testSpec(t,
		"| This Is\n  {{^boolean}}\n|\n  {{/boolean}}\n| A Line\n",
		"| This Is\n|\n| A Line\n",
		map[string]interface{}{"boolean": false})
}

func TestInvertedStandaloneLineEndings(t *testing.T) {
	testSpec(t,
		"|\r\n{{^boolean}}\r\n{{/boolean}}\r\n|",
		"|\r\n|",
		map[string]interface{}{"boolean": false})
}

func TestInvertedStandaloneWithoutPreviousLine(t *testing.T) {
	testSpec(t,
		"  {{^boolean}}\n^{{/boolean}}\n/",
		"^\n/",
		map[string]interface{}{"boolean": false})
}

func TestInvertedStandaloneWithoutNewline(t *testing.T) {
	testSpec(t,
		"^{{^boolean}}\n/\n  {{/boolean}}",
		"^\n/\n",
		map[string]interface{}{"boolean": false})
}

func TestInvertedPadding(t *testing.T) {
	testSpec(t,
		"|{{^ boolean }}={{/ boolean }}|",
		"|=|",
		map[string]interface{}{"boolean": false})
}

func TestPartialsBasicBehavior(t *testing.T) {
	generatePartial("text.mustache", "from partial")
	defer os.Remove("text.mustache")
	testSpec(t,
		"\"{{>text}}\"",
		"\"from partial\"",
		map[string]interface{}{})
}

func TestPartialsFailedLookup(t *testing.T) {
	testSpec(t,
		"\"{{>text}}\"",
		"\"\"",
		map[string]interface{}{})
}

func TestPartialsContext(t *testing.T) {
	generatePartial("partial.mustache", "*{{text}}*")
	defer os.Remove("partial.mustache")
	testSpec(t,
		"\"{{>partial}}\"",
		"\"*content*\"",
		map[string]interface{}{"text": "content"})
}

func TestPartialsRecursion(t *testing.T) {
	generatePartial("node.mustache", "{{content}}<{{#nodes}}{{>node}}{{/nodes}}>")
	defer os.Remove("node.mustache")
	testSpec(t,
		"{{>node}}",
		"X<Y<>>",
		map[string]interface{}{"content": "X", "nodes": []interface{}{map[string]interface{}{"nodes": []interface{}{}, "content": "Y"}}})
}

func TestPartialsSurroundingWhitespace(t *testing.T) {
	generatePartial("partial.mustache", "\t|\t")
	defer os.Remove("partial.mustache")
	testSpec(t,
		"| {{>partial}} |",
		"| \t|\t |",
		map[string]interface{}{})
}

func TestPartialsInlineIndentation(t *testing.T) {
	generatePartial("partial.mustache", ">\n>")
	defer os.Remove("partial.mustache")
	testSpec(t,
		"  {{data}}  {{> partial}}\n",
		"  |  >\n>\n",
		map[string]interface{}{"data": "|"})
}

func TestPartialsStandaloneLineEndings(t *testing.T) {
	generatePartial("partial.mustache", ">")
	defer os.Remove("partial.mustache")
	testSpec(t,
		"|\r\n{{>partial}}\r\n|",
		"|\r\n>|",
		map[string]interface{}{})
}

func TestPartialsStandaloneWithoutPreviousLine(t *testing.T) {
	generatePartial("partial.mustache", ">\n>")
	defer os.Remove("partial.mustache")
	testSpec(t,
		"  {{>partial}}\n>",
		"  >\n  >>",
		map[string]interface{}{})
}

func TestPartialsStandaloneWithoutNewline(t *testing.T) {
	generatePartial("partial.mustache", ">\n>")
	defer os.Remove("partial.mustache")
	testSpec(t,
		">\n  {{>partial}}",
		">\n  >\n  >",
		map[string]interface{}{})
}

func TestPartialsStandaloneIndentation(t *testing.T) {
	generatePartial("partial.mustache", "|\n{{{content}}}\n|\n")
	defer os.Remove("partial.mustache")
	testSpec(t,
		"\\\n {{>partial}}\n/\n",
		"\\\n |\n <\n->\n |\n/\n",
		map[string]interface{}{"content": "<\n->"})
}

func TestPartialsPaddingWhitespace(t *testing.T) {
	generatePartial("partial.mustache", "[]")
	defer os.Remove("partial.mustache")
	testSpec(t,
		"|{{> partial }}|",
		"|[]|",
		map[string]interface{}{"boolean": true})
}

func TestSectionsTruthy(t *testing.T) {
	testSpec(t,
		"\"{{#boolean}}This should be rendered.{{/boolean}}\"",
		"\"This should be rendered.\"",
		map[string]interface{}{"boolean": true})
}

func TestSectionsFalsey(t *testing.T) {
	testSpec(t,
		"\"{{#boolean}}This should not be rendered.{{/boolean}}\"",
		"\"\"",
		map[string]interface{}{"boolean": false})
}

func TestSectionsContext(t *testing.T) {
	testSpec(t,
		"\"{{#context}}Hi {{name}}.{{/context}}\"",
		"\"Hi Joe.\"",
		map[string]interface{}{"context": map[string]interface{}{"name": "Joe"}})
}

func TestSectionsDeeplyNestedContexts(t *testing.T) {
	testSpec(t,
		"{{#a}}\n{{one}}\n{{#b}}\n{{one}}{{two}}{{one}}\n{{#c}}\n{{one}}{{two}}{{three}}{{two}}{{one}}\n{{#d}}\n{{one}}{{two}}{{three}}{{four}}{{three}}{{two}}{{one}}\n{{#e}}\n{{one}}{{two}}{{three}}{{four}}{{five}}{{four}}{{three}}{{two}}{{one}}\n{{/e}}\n{{one}}{{two}}{{three}}{{four}}{{three}}{{two}}{{one}}\n{{/d}}\n{{one}}{{two}}{{three}}{{two}}{{one}}\n{{/c}}\n{{one}}{{two}}{{one}}\n{{/b}}\n{{one}}\n{{/a}}\n",
		"1\n121\n12321\n1234321\n123454321\n1234321\n12321\n121\n1\n",
		map[string]interface{}{"a": map[string]interface{}{"one": 1}, "b": map[string]interface{}{"two": 2}, "c": map[string]interface{}{"three": 3}, "d": map[string]interface{}{"four": 4}, "e": map[string]interface{}{"five": 5}})
}

func TestSectionsList(t *testing.T) {
	testSpec(t,
		"\"{{#list}}{{item}}{{/list}}\"",
		"\"123\"",
		map[string]interface{}{"list": []interface{}{map[string]interface{}{"item": 1}, map[string]interface{}{"item": 2}, map[string]interface{}{"item": 3}}})
}

func TestSectionsEmptyList(t *testing.T) {
	testSpec(t,
		"\"{{#list}}Yay lists!{{/list}}\"",
		"\"\"",
		map[string]interface{}{"list": []interface{}{}})
}

func TestSectionsDoubled(t *testing.T) {
	testSpec(t,
		"{{#bool}}\n* first\n{{/bool}}\n* {{two}}\n{{#bool}}\n* third\n{{/bool}}\n",
		"* first\n* second\n* third\n",
		map[string]interface{}{"two": "second", "bool": true})
}

func TestSectionsNestedTruthy(t *testing.T) {
	testSpec(t,
		"| A {{#bool}}B {{#bool}}C{{/bool}} D{{/bool}} E |",
		"| A B C D E |",
		map[string]interface{}{"bool": true})
}

func TestSectionsNestedFalsey(t *testing.T) {
	testSpec(t,
		"| A {{#bool}}B {{#bool}}C{{/bool}} D{{/bool}} E |",
		"| A  E |",
		map[string]interface{}{"bool": false})
}

func TestSectionsContextMisses(t *testing.T) {
	testSpec(t,
		"[{{#missing}}Found key 'missing'!{{/missing}}]",
		"[]",
		map[string]interface{}{})
}

func TestSectionsImplicitIteratorString(t *testing.T) {
	testSpec(t,
		"\"{{#list}}({{.}}){{/list}}\"",
		"\"(a)(b)(c)(d)(e)\"",
		map[string]interface{}{"list": []interface{}{"a", "b", "c", "d", "e"}})
}

func TestSectionsImplicitIteratorInteger(t *testing.T) {
	testSpec(t,
		"\"{{#list}}({{.}}){{/list}}\"",
		"\"(1)(2)(3)(4)(5)\"",
		map[string]interface{}{"list": []interface{}{1, 2, 3, 4, 5}})
}

func TestSectionsImplicitIteratorDecimal(t *testing.T) {
	testSpec(t,
		"\"{{#list}}({{.}}){{/list}}\"",
		"\"(1.1)(2.2)(3.3)(4.4)(5.5)\"",
		map[string]interface{}{"list": []interface{}{1.1, 2.2, 3.3, 4.4, 5.5}})
}

func TestSectionsDottedNamesTruthy(t *testing.T) {
	testSpec(t,
		"\"{{#a.b.c}}Here{{/a.b.c}}\" == \"Here\"",
		"\"Here\" == \"Here\"",
		map[string]interface{}{"a": map[string]interface{}{"b": map[string]interface{}{"c": true}}})
}

func TestSectionsDottedNamesFalsey(t *testing.T) {
	testSpec(t,
		"\"{{#a.b.c}}Here{{/a.b.c}}\" == \"\"",
		"\"\" == \"\"",
		map[string]interface{}{"a": map[string]interface{}{"b": map[string]interface{}{"c": false}}})
}

func TestSectionsDottedNamesBrokenChains(t *testing.T) {
	testSpec(t,
		"\"{{#a.b.c}}Here{{/a.b.c}}\" == \"\"",
		"\"\" == \"\"",
		map[string]interface{}{"a": map[string]interface{}{}})
}

func TestSectionsSurroundingWhitespace(t *testing.T) {
	testSpec(t,
		" | {{#boolean}}\t|\t{{/boolean}} | \n",
		" | \t|\t | \n",
		map[string]interface{}{"boolean": true})
}

func TestSectionsInternalWhitespace(t *testing.T) {
	testSpec(t,
		" | {{#boolean}} {{! Important Whitespace }}\n {{/boolean}} | \n",
		" |  \n  | \n",
		map[string]interface{}{"boolean": true})
}

func TestSectionsIndentedInlineSections(t *testing.T) {
	testSpec(t,
		" {{#boolean}}YES{{/boolean}}\n {{#boolean}}GOOD{{/boolean}}\n",
		" YES\n GOOD\n",
		map[string]interface{}{"boolean": true})
}

func TestSectionsStandaloneLines(t *testing.T) {
	testSpec(t,
		"| This Is\n{{#boolean}}\n|\n{{/boolean}}\n| A Line\n",
		"| This Is\n|\n| A Line\n",
		map[string]interface{}{"boolean": true})
}

func TestSectionsIndentedStandaloneLines(t *testing.T) {
	testSpec(t,
		"| This Is\n  {{#boolean}}\n|\n  {{/boolean}}\n| A Line\n",
		"| This Is\n|\n| A Line\n",
		map[string]interface{}{"boolean": true})
}

func TestSectionsStandaloneLineEndings(t *testing.T) {
	testSpec(t,
		"|\r\n{{#boolean}}\r\n{{/boolean}}\r\n|",
		"|\r\n|",
		map[string]interface{}{"boolean": true})
}

func TestSectionsStandaloneWithoutPreviousLine(t *testing.T) {
	testSpec(t,
		"  {{#boolean}}\n#{{/boolean}}\n/",
		"#\n/",
		map[string]interface{}{"boolean": true})
}

func TestSectionsStandaloneWithoutNewline(t *testing.T) {
	testSpec(t,
		"#{{#boolean}}\n/\n  {{/boolean}}",
		"#\n/\n",
		map[string]interface{}{"boolean": true})
}

func TestSectionsPadding(t *testing.T) {
	testSpec(t,
		"|{{# boolean }}={{/ boolean }}|",
		"|=|",
		map[string]interface{}{"boolean": true})
}
